# Generated by Django 5.0.3 on 2024-04-04 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_comments', '0002_alter_comments_id_alter_comments_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0)),
                ('image', models.URLField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
